### ISSUE TITLE
Browser differences

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#1061]
Currently found differences that might need to be fixed:

Firefox:
- Gives console warnings for a number of libraries:
```
Source map error: TypeError: [library].js.map is not a valid URL.
Resource URL: webpack:///./node_modules/halogenium/lib/[library].js?
Source Map URL: [library].js.map
```
- Cannot seem to hover/click on remove icon for reference users & groups (Even though it works in Chrome)

**Comment by igboyes** [comment]
I am not going to worry about this. Source maps are not built in the development webpack configuration so it makes sense that it wouldn't find them.

I have dealt with this issue before. I can't remeber exactly what the issue is but I think it is something to do with HTML rules valid children of `<button />` or have `onClick` events on elements in buttons.

I checked and the user and group list items do get rendered as `<button />` elements. You can fix this issue by using `<div>` instead. I don't think `react-bootstrap` supports setting the element type, but you can just use the bootstrap CSS if necessary (ie. `<div className="list-group-item" />`).

**Comment by igboyes** [comment]
By the way, Chrome breaks the HTML spec for that rule, which is why it works.
