### ISSUE TITLE
Job progress bar visual bug

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1115]
When a job in the list is removed the job item that moves into its previous position undergoes an progress bar change animation.

Are the keys for job items array indexes or document ids? Changing to ids might be a quick fix.

**Comment by Miminko** [comment]
The keys are for array indexes since they are faster to access than searching within the array entries for the id property. Changing to ids seems to result in the same animation.
I think its due to the progress bar animation defined in `style/bootstrap/progress-bars.less`.

The list entry only re-renders the entries that receive new `progress` values, and the `<ProgressBar />` component will show the animation when `prevProps.now !== this.props.now` where `prevProps.now` was supplied by the old entry's progress before the list shift, and `this.props.now` is supplied by the new entry progress.

I'm not sure if there is a way to avoid the animation caused by the progress prop change and keep the list render optimization, I think the alternative would be to go back to controlling the rendering of the entire list?

**Comment by igboyes** [comment]
Let's revert to the old rendering method.
