### ISSUE TITLE
Host subtraction mapping percentage - specific example

### ISSUE THREAD

**Issue by tranlt** [virtool/virtool#1747]
Sample Q18B has more host reads mapped than the total number of reads. Wondering how pathoscope determined this mapping percentage?

**Comment by igboyes** [comment]
Example:
![image](https://user-images.githubusercontent.com/5943558/77117126-9b7cc600-69ee-11ea-80b1-78a5859f54a7.png)

Problem is due to inflation of subtracted read numbers in samples where there are a lot of real subtractions and a lot of multi-mapping.

The bug only affects the subtracted read count, not the actual virus detection.

Will be fixed in next version.
