### ISSUE TITLE
Failed NuV

### ISSUE THREAD

**Issue by jp15nw** [virtool/virtool#1859]
I had this same issue a month ago and it was solved but it is happening again. I've attached the link to the old issue at the bottom. I get the same error messages and the log file looks like same. I tried the same solution and I have 45849560 kB of free memory. But every NuV I run ends up failing. 
I'm hoping for any suggestions besides upgrading the machine.

https://github.com/virtool/virtool/issues/1828

[Log File-Failed NuV.pdf](https://github.com/virtool/virtool/files/4732734/Log.File-Failed.NuV.pdf)

**Comment by igboyes** [comment]
Looking at the log, the thread and memory limits for SPAdes are the reverse of what I'd expect.
```text
2020-06-04T14:55:56.169000 b' Threads: 53'
2020-06-04T14:55:56.169000 b' Memory limit (in Gb): 23'
```
Can you confirm your config values for job resources (`proc`, `mem`, `lg_proc`, etc).

**Comment by jp15nw** [comment]
This is what it is currently set to
     "proc": 54,
     "mem": 56 ,
     "lg_proc": 54,
     "lg_mem": 23

**Comment by igboyes** [comment]
I apologize is my explanation in #1828 was confusing. I didn't realize you had such a high thread count. Usually a system is configured so that there is 2-4x as many GBs of memory as cores.

With your configuration, you will only be able to run one large job (NuVs) at a time. The `lg_proc` setting will make the Virtool instance reach its limit set by `proc`. At the same time, you are limiting yourself to 23 GB of memory. If you want to dedicate all the instance resources to one job the config should be:
```json
{
  "proc": 54,
  "mem": 56 ,
  "lg_proc": 54,
  "lg_mem": 56
}
```

Hope that makes sense.

**Comment by jp15nw** [comment]
I am not sure what the thread count is. I just kept the lg_mem to what you said before and it worked for a while. But I while try these config values and let you know if it works. Thank you!

**Comment by jp15nw** [comment]
the returned value is 56

**Comment by igboyes** [comment]
Also, `lsmem`. What is the value for **Total online memory**?

**Comment by jp15nw** [comment]
That value is 64G

**Comment by igboyes** [comment]
Okay cool. If you guys get a chance, I would suggest doubling the memory on that machine.
