### ISSUE TITLE
Retrieve sequences of contigs from Virtool

### ISSUE THREAD

**Issue by mfall** [virtool/virtool#2081]
Hi,
thanks a lot for this amazing tool. I am a user of virtool, Virfind and V-pipe and I am planning to have VirAnnot. I can fairly say that I love using virtool. However, there is an improvements (features) that will be awesome to have if possible.

When using Pathoscope workflow: Possibility to retrieve sequences of contigs from Virtool after a positive detection of a given virus, for further analysis. 

Regards, 
Mamadou

**Comment by MikeERott** [comment]
Hi, Manadou. Thanks for the suggestion. You are not the first to ask for this feature. 
Because Pathoscope uses a readmapping approach, it does not generate contigs. A possible solution might be to add an assembler option using the only the reads mapping to an OTU and providing that as an output/export option. It is something to consider. 
 
 NuVs on the other hand does create contigs using SPAdes and these contigs can be exported for further analysis.
