### ISSUE TITLE
Add warning for special characters in the name of subtraction

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#293]
I created a subtraction with "( )" in the name. Got error when Bowtie was executing. It looks like the character "(" and ")" are unknown syntax for Bowtie. 
Am I observing correctly?
![screenshot from 2017-12-04 17 06 05](https://user-images.githubusercontent.com/8636318/33579002-4e3521c8-d916-11e7-9c07-d20edbc0a316.png)

**Comment by igboyes** [comment]
Yes, you are correct.

I previously had another field for subtractions, which was an alternative name for the subtraction. Maybe it would be a good idea to bring this back instead of you having to put _peach_ in brackets?

In the meantime, I should be able to do a quick fix that will allow non-alpha characters in the subtraction name. I am just about to publish beta.11. I'll put the fix in beta.12.

**Comment by maplexuci** [comment]
I think it would be a good idea to add a common name field. 
When samples or references are less, it is always easy to manage, but when they are populated, it would be good to quickly distinguish among different names.

**Comment by igboyes** [comment]
I've fixed this for now. Names containing brackets will work after beta.12.

Subtraction nicknames or common names will be brought back later.
