### ISSUE TITLE
Consistent input and form errors

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#404]
Develop consistent standard for styling form and input errors.

#### Error Types
1. Input error
- specific input values are unacceptable
- errors appear the same whether they where generated on the client or server
- deprecate `<Popover />`-based errors

2. Form error
- form input taken as a whole is invalid
- example is incorrect username and password
- display of error makes it obvious it applies to the whole form

#### Style Ideas
- no validation icons necessary
- apply color to input element border
- position input-specific errors below bottom-left or -right corner of input
- make it obvious form errors apply to whole form
- take a look at [HTML5 validation](https://pageclip.co/blog/2018-02-20-you-should-use-html5-form-validation.html)

#### To Do
- [x] modify base `<Input />` to easily add error messages to component
- [x] make sure changes to `<Input />` are compatible with `<InputSave />`
- [x] make all occurences of `<Input />` in the app consistently styled

**Comment by Miminko** [comment]
- For components that use InputSave (i.e. in the settings tab), do they need to show input/form errors as well? Or just be able to use the Input component with no problems?
- for the creating sample modal, which fields are required? At the moment only a file needs to be selected for a sample to be created, yet will show request errors on sample deletion due to name, etc fields being blank

**Comment by Miminko** [comment]
- the create user form also allows blank entries that cannot be later edited/deleted
