### ISSUE TITLE
Depth value in Pathoscope report

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#906]
1. Remove _Best Hit_ in Pathoscope UI and replace with _Depth_.
  Depth is the mean depth over the length of a reference sequence. Round to whole number.

2. Calculate depth
  Review pathocope `Viewer.js`. Calculate mean depth accurately for each logical level (sequence, isolate, virus).

**Comment by Miminko** [comment]
For the sequence level mean depth, is it already calculated as the `sequences[i].depth` value in the store? Or does this depth value mean something else? It doesn't seem to be used anywhere.

**Comment by Miminko** [comment]
I manually calculated the sequence depth means on the client side and the results matched with the store's `sequence[i].depth` values, so this must correspond with that particular sequence's mean depth value.

When calculating the isolate level mean depth, should I ignore sequences with no align/reads/depth values? Including them would bring down the average depth value since it will just add to the total length. Or should it depend on whether "filter > Isolates" is checked?
